### ISSUE TITLE
[css-ruby] replaced annotation containers and base containers are nonsensical

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#526]
A resolution was made for [csswg-drafts/#6000](https://github.com/w3c/csswg-drafts/issues/6000).

**\[css\-ruby\] replaced annotation containers and base containers are nonsensical**

* RESOLVED: if you are a replaced element with dipslay of base or annotation container without changing the computed value they're treated as base or annotation respectively

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6000#issuecomment-824188125)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @upsuper - do you recall if this is how Firefox's implementation works?

(And if it's not how our impl works, do you think this change makes sense or have any concerns about us making this change?)

**Comment by upsuper** [comment]
Based on some experiments, I don't think it matches how it currently works. My understanding is that, for replaced elements, we currently ignore `<display-internal>`, and only really uses `<display-outside>`, so the current behavior treats a replaced element with `ruby-{base,text}-container` as just `inline` as mentioned by @emilio.

I don't think it's useful to define the behavior this way. Basically I don't think any reasonable developer would try to assign a ruby internal display value to a replaced element. But I don't know how replaced elements should be handled in general with weird display value. If it's not defined anywhere, it's probably better to be defined in a general term, rather than case-by-case for each display values.

Also it doesn't seem to me that we have any precedence for this, e.g. we don't handle replaced element with table internal `display` values specially. I don't quite see why it's important to handle ruby internal `display` values specially.

So I don't think I agree with this decision.

Regarding making this change, this change would mostly be inside the frame constructor. It's probably not terribly hard to implement, but in my opinion it would be extra code to handle a meaningless special case. (We would probably need to wrap a replaced element with those `display` values with an extra fc item of the corresponding ruby internal.)

**Comment by dholbert** [comment]
Thanks, @upsuper. The CSSWG ended up re-resolving on your suggested behavior.  (mozilla-apprentice filed #530 to record this.)
