### ISSUE TITLE
[css-grid] Resolution of percentage row tracks and gutters with indefinite height

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#617]
A resolution was made for [csswg-drafts/#5566](https://github.com/w3c/csswg-drafts/issues/5566).

**\[css\-grid\] Resolution of percentage row tracks and gutters with indefinite height**

* RESOLVED: Close no change

[Discussion.](https://github.com/w3c/csswg-drafts/issues/5566#issuecomment-896987749)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @MatsPalmgren , just want to be sure this is on your radar since you had weighed in on the spec-issue here.

Closing this mozilla-apprentice issue since there's no-change, and we already have https://bugzilla.mozilla.org/show_bug.cgi?id=1481876 to cover implementing the currently-specced behavior, I think.
