### ISSUE TITLE
[css-scroll-animations] Rethinking declarative syntax for scroll-linked animations

### ISSUE THREAD

**Issue by mozilla-apprentice** [heycam/csswg-decisions#647]
Resolutions were made for [csswg-drafts/#6674](https://github.com/w3c/csswg-drafts/issues/6674).

**\[css\-scroll\-animations\] Rethinking declarative syntax for scroll\-linked animations**

* RESOLVED: Adopt fantasai/miriam's new direction for the declarative side of scroll\-linked animations
* RESOLVED: Add flackr as editor to scroll\-animations, move Majid to Former

[Discussion.](https://github.com/w3c/csswg-drafts/issues/6674#issuecomment-930334244)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @BorisChiou to be sure he's aware of this resolution/issue.

(Not sure if we need a specific bug for this resolution, or if this can just be merged into the existing in-progress work.)

**Comment by BorisChiou** [comment]
Yes. I noticed this issue and I'm trying to figure out a good way to implement this because it's still not clear which version we want in the future. I'd like to implement scroll-linked animation partially based on the current version (excluding the offsets part because offsets will be dropped), and use a new bug to match the new spec (once this spec issue gets landed).

**Comment by BorisChiou** [comment]
bug

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1733260
